export const DATA = {
    columns: [
        {
            field: "id",
            headerName: "id",
            dataType: "int",
            editable: "false",
        },
        {
            field: "Name",
            headerName: "Name",
            dataType: "nvarchar",
        },
        {
            field: "Email",
            headerName: "Email",
            dataType: "nvarchar",
        },
        {
            field: "Contact",
            headerName: "Contact",
            dataType: "numeric",
        },
        {
            field: "Gender",
            headerName: "Gender",
            dataType: "nvarchar",
        },
        {
            field: "Hobbies",
            headerName: "Hobbies",
            dataType: "nvarchar",
        },
        {
            field: "City",
            headerName: "City",
            dataType: "nvarchar",
        },
        {
            field: "Date",
            headerName: "Date",
            dataType: "nvarchar",
        },
    ],
    rows: [
        {
            id: 1,
            Name: "nihal",
            Email: "nihal.bagdadi@irisdame.in",
            Contact: 1231321,
            Gender: null,
            Hobbies: null,
            Date: "22/09/2010",
        },
        {
            id: 2,
            Name: "faeez",
            Email: "faeez.shaikh@irisdame.in",
            Contact: 852369,
            Gender: null,
            Hobbies: null,
            Date: "14/09/2010",
        },
        {
            id: 3,
            Name: "farhan",
            Email: "farhan.khadpolker@irisdame.in",
            Contact: 745896,
            Gender: null,
            Hobbies: null,
            Date: "24/09/2022",
        },
        {
            id: 4,
            Name: "saud",
            Email: "saud.chougle@irisdame.in",
            Contact: 8556,
            Gender: null,
            Hobbies: null,
            Date: "10/09/2000",
        },
        {
            id: 8,
            Name: "priyanka",
            Email: "priyakapalande@gmail.com",
            Contact: 223434234,
            Gender: "Felmale",
            Hobbies: "Reading",
            City: "Pune",
            Date: "01/09/2012",
        },
        {
            id: 10,
            Name: "12:23:12.0000000",
            Email: "Priyanka@gmail.com",
            Contact: 34,
            Gender: "Felmale",
            Hobbies: "Reading",
            City: "Pune",
            Date: "11/09/2022",
        },
        {
            id: 12,
            Name: "a",
            Email: "aa@gmail.com",
            Contact: 222222,
            Gender: "Male",
            Hobbies: "Reading, Chess",
            City: "Pune",
            Date: "30/04/2024",
        },
        {
            id: 13,
            Name: "b",
            Email: "bb@gmail.com",
            Contact: 3333,
            Gender: "Felmale",
            Hobbies: "Reading, Cricket",
            City: "Nagpur",
        },
        {
            id: 14,
            Name: "c",
            Email: "cc@gmail.com",
            Contact: 4444444,
            Gender: "Male",
            Hobbies: "Reading, Chess, Cricket",
            City: "Pune",
        },
        {
            id: 15,
            Name: "d",
            Email: "dd@gmail.com",
            Contact: 555555,
            Gender: "Male",
            Hobbies: "Reading, Chess, Cricket",
            City: "Mumbai",
        },
    ],
};

export const ChatData = {
    chat: [
        {
            "formId": "84789087-4553-47f1-a3ahe11",
            "chatId": "rB",
            "content": "hi12345 h5W2",
            "messageType": "text",
            "contentType": "text",
            "status": "active",
            "senderUserId": 'qaoOuPDbMdS6gwe0DLv1KpwEgth2'
          },
          {
            "formId": "84789087-4553-47f1-a3ahe11",
            "chatId": "Nm",
            "content": "hi12345 7Eg3",
            "messageType": "text",
            "contentType": "text",
            "status": "active",
            "senderUserId": "T7rDJmivCJeAk1SNRTSCadJU5lx1"
          },
          {
            "formId": "84789087-4553-47f1-a3ahe11",
            "chatId": "N7",
            "content": "hi12345 lRjS",
            "messageType": "text",
            "contentType": "text",
            "status": "active",
            "senderUserId": 'qaoOuPDbMdS6gwe0DLv1KpwEgth2'
          },
          {
            "formId": "84789087-4553-47f1-a3ahe11",
            "chatId": "9Z",
            "content": "hi12345 oaFz",
            "messageType": "text",
            "contentType": "text",
            "status": "active",
            "senderUserId": "T7rDJmivCJeAk1SNRTSCadJU5lx1"
          },
          {
            "formId": "84789087-4553-47f1-a3ahe11",
            "chatId": "L0",
            "content": "hi12345 ETPn",
            "messageType": "text",
            "contentType": "text",
            "status": "active",
            "senderUserId": 'qaoOuPDbMdS6gwe0DLv1KpwEgth2'
          },
          {
            "formId": "84789087-4553-47f1-a3ahe11",
            "chatId": "4J",
            "content": "hi12345 NPm3",
            "messageType": "text",
            "contentType": "text",
            "status": "active",
            "senderUserId": "T7rDJmivCJeAk1SNRTSCadJU5lx1"
          },
    ],
};
